Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
      ## 2 GB of RAM ##
      vb.memory = "2048"
    end
    config.vm.define "basic" do |script|
      ## Linux distro: Ubuntu ##
      basic.vm.box = "ubuntu/groovy64"
      ## Machine hostname ##
      basic.vm.hostname = "basic"
      ## Host only network ##
      basic.vm.network "private_network", ip: "192.168.56.23"
    end
end
